[project]
name = "math"
version = "0.1.0"
authors = [{ name = "Alvin", email = "quhao317@163.com" }]
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.9.2",
    "data-science-types>=0.2.23",
    "numpy>=1.26.4",
    "pygame>=2.6.1",
    "pyopengl>=3.1.7",
]
requires-python = ">=3.12"
readme = "README.md"
license = { text = "MIT" }

[project.optional-dependencies]
test = ["pytest>=8.3.3"]
lint = ["autopep8>=2.3.1", "mypy>=1.13.0"]

[tool.pdm.scripts]
check = { composite = ["mypy src", "autopep8 src tests"] }
test = "pytest -v -s tests"
clean = "clear.py"

[tool.mypy]
python_version = '3.12'
strict = true
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
disallow_untyped_decorators = false
disallow_untyped_calls = false
disallow_subclassing_any = false
exclude = ['migration/scripts/.+?\.py$']

[tool.autopep8]
max_line_length = 120
ignore = ['E501', 'W6']
in-place = true
recursive = true
jobs = -1
aggressive = 3

[tool.pytest.ini_options]
addopts = '-vs -p no:warnings'
