version: "3.9"
services:
  percona:
    image: percona/percona-server
    container_name: percona
    restart: always
    privileged: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 256M
        reservations:
          memory: 100M
    env_file:
      - ./env/percona.env
    ports:
      - 3306:3306
    volumes:
      - ./conf/default.cnf:/etc/my.cnf.d/default.cnf:ro
      - ./sql/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql:ro
      - ./log:/var/log/mysql
      - percona_data:/var/lib/mysql
    networks:
      - percona_network
networks:
  percona_network:
volumes:
  percona_data:
