requires = ["tox>=4.19"]
env_list = [
    "py313", # 可以写为 "3.13"
    # "py312", # 可写为 "3.12"
    "type",
    "lint",
]

[env_run_base]
description = "Run unit tests"
deps = [
    "pytest>=8.3",
]
allowlist_externals = ["pytest"]
commands = [
    ["pytest"],
]

[env.py313]
description = "run tests on python 3.13"

[env.py312]
description = "run tests on python 3.12"

[env.type]
description = "run type check on code base"
deps = [
    "mypy>=1.15",
]
commands = [
    ["mypy", "."],
]

[env.lint]
description = "run linting on code base"
deps = [
    "autopep8>=2.3",
    "pycln>=2.5",
]
commands = [
    ["autopep8", "."],
    ["pycln", "--config=pycln.cfg"],
]
