[project]
name = "uv-workspace-utils"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alvin", email = "quhao317@163.com" },
]
requires-python = ">=3.13"
dependencies = [
]

[dependency-groups]
ext = [
    "invoke>=2.2.0",
]
lint = [
    "autopep8>=2.3.2",
    "pycln>=2.5.0",
]
test = [
    "pytest>=8.4.2",
    "pytest-sugar>=1.1.1",
]
type = [
    "mypy>=1.17.1",
    "mypy-extensions>=1.1.0",
]

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[tool.pycln]
path = "."
all = true

[tool.mypy]
files = [
    ".",
]
strict = true
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
disallow_untyped_decorators = false
check_untyped_defs = true

[tool.autopep8]
max_line_length = 120
ignore = [
    'E501',
    'W6',
]
jobs = -1
in-place = true
recursive = true
aggressive = 3

[tool.pytest.ini_options]
addopts = [
    '-s',
]
testpaths = [
    'tests',
]
