[project]
name = "database_demo"
version = "0.1.0"
authors = [{ name = "Alvin", email = "quhao317@163.com" }]
dependencies = [
    "sqlalchemy>=2.0.29",
    "dbutils>=3.1.0",
    "pymysql>=1.1.0",
    "alembic>=1.13.1",
    "cryptography>=42.0.5",
    "pymongo>=4.6.2",
    "werkzeug>=3.0.1",
    "mongoengine>=0.28.2",
    "blinker>=1.7.0",
    "peewee>=3.17.1",
    "pysqlite3>=0.5.2",
]
requires-python = ">=3.12"
readme = "README.md"
license = { text = "MIT" }

[project.optional-dependencies]
lint = ["mypy>=1.9.0", "autopep8>=2.1.0"]
test = ["pytest>=8.1.1", "factory-boy>=3.3.0"]

[tool.pdm.scripts]
check = { composite = ["mypy src", "autopep8 src tests"] }
test = "pytest -v -s tests"
clean = { composite = [
    "rm -rf .pdm-build",
    "rm -rf .mypy_cache",
    "rm -rf .pytest_cache",
    "rm -rf dist",
    'find src -type d -name "__pycache__" -exec rm -rf {} +',
    'find tests -type d -name "__pycache__" -exec rm -rf {} +',
] }

[tool.mypy]
python_version = '3.12'
strict = true
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
disallow_untyped_decorators = false
disallow_untyped_calls = false
disallow_subclassing_any = false
exclude = ['migration/scripts/.+?\.py$']

[tool.autopep8]
max_line_length = 120
ignore = ['E501', 'W6']
in-place = true
recursive = true
jobs = -1
aggressive = 3

[tool.pytest.ini_options]
# testpaths = ['tests']
# pythonpath = ['src']
addopts = '-vs -p no:warnings'
