---
version: "3"
services:
  mongo:
    image: "mongo:4.4.6"
    container_name: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - "mongo-data:/data"
    networks:
      - "mongo-network"
networks:
  mongo-network:
    external: false
volumes:
  mongo-data:
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
