version: "3.9"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    privileged: true
    env_file:
      - env/mongo.env
    ulimits:
      nproc: 65535
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 256M
        reservations:
          memory: 100M
    ports:
      - 27017:27017
    volumes:
      - mongo_data_db:/data/db
      - mongo_data_config:/data/configdb
    networks:
      - mongo_network
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - env/express.env
    networks:
      - mongo_network
networks:
  mongo_network:
volumes:
  mongo_data_db:
  mongo_data_config:

