[project]
name = "uv-package"
version = "0.1.0"
description = "UV for Python Package Demo"
readme = "README.md"
authors = [
    { name = "AlvinQ", email = "quhao317@163.com" },
]
requires-python = ">=3.13"
dependencies = [
    "uv-lib",
]

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"

[project.scripts]
uv-package = "uv_package:run"

[dependency-groups]
ext = [
    "invoke>=2.2.0",
]
lint = [
    "autopep8>=2.3.2",
    "pycln>=2.5.0",
]
test = [
    "pytest>=8.4.0",
    "pytest-sugar>=1.0.0",
]
type = [
    "mypy>=1.16.0",
    "mypy-extensions>=1.1.0",
]

[tool.uv.sources]
uv-lib = { path = "../lib" }

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[tool.pycln]
path = "."
all = true
exclude = '\.history'

[tool.mypy]
files = [
    ".",
]
strict = true
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
disallow_untyped_decorators = false
check_untyped_defs = true
exclude = '\.history'

[tool.autopep8]
max_line_length = 120
ignore = [
    'E501',
    'W6',
]
in-place = true
recursive = true
jobs = -1
aggressive = 3
exclude = '.history'

[tool.pytest.ini_options]
addopts = [
    '-s',
]
testpaths = [
    'tests',
]
