[project]
name = "pdm-uv"
version = "0.1.0"
description = "Integrate PDM and UV together"
authors = [
    { name = "Alvin", email = "quhao317@163.com" },
]
dependencies = [
]
requires-python = ">=3.13"
readme = "README.md"
license = { text = "MIT" }

[dependency-groups]
lint = [
    "autopep8>=2.3.2",
    "pycln>=2.5.0",
]
type = [
    "mypy>=1.15.0",
    "mypy-extensions>=1.1.0",
]
test = [
    "pytest>=8.3.5",
    "pytest-sugar>=1.0.0",
]

[tool.pdm]
distribution = false

[tool.pdm.scripts]
start = "main.py"
check = { composite = [
    "lint",
    "type",
    "test",
] }
lint = { composite = [
    "pycln --config=pyproject.toml .",
    "autopep8 .",
] }
type = { composite = [
    "mypy .",
] }
test = "pytest"
clean = { call = "clear:main" }

[tool.pycln]
path = '.'
exclude = '\.history'

[tool.mypy]
python_version = "3.13"
strict = true
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
disallow_untyped_decorators = false
check_untyped_defs = true
exclude = [
    '.venv',
    '.history',
]

[tool.autopep8]
max_line_length = 120
ignore = [
    'E501',
    'W6',
]
in-place = true
recursive = true
jobs = -1
aggressive = 3

[tool.pytest.ini_options]
addopts = [
    '-vvs',
]
testpaths = [
    'tests',
]
