[project]
name = "fastapi_demo"
version = "0.1.0"
authors = [{ name = "Alvin", email = "quhao317@163.com" }]
dependencies = [
    # 生产环境依赖
    "fastapi[all]>=0.115.6",
]
requires-python = "==3.13.*"
readme = "README.md"
license = { text = "MIT" }

[project.optional-dependencies]
test = [
    "pytest>=8.3.4",
    "pytest-mock>=3.14.0",
    "pytest-asyncio>=0.25.2",
    "httpx>=0.28.1",
]
lint = [ # 代码样式检测依赖
    "mypy>=1.9.0",
    "autopep8>=2.1.0",
]

[tool.pdm.scripts]
check = { composite = ["mypy src", "autopep8 src tests"] }
test = "pytest -v -s tests"
clean = { call = "clear:main" }
type_install = "mypy --install-types"

[tool.mypy]
python_version = '3.13.*'
strict = true
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
disallow_untyped_decorators = false
disallow_untyped_calls = false
disallow_subclassing_any = false
exclude = []

[tool.autopep8]
max_line_length = 120
ignore = ['E501', 'W6', 'E261']
in-place = true
recursive = true
jobs = -1
aggressive = 3

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
addopts = "-svv"
