[project]
name = "pdm-app"
version = "1.0.0"
description = "PDM App demo"
authors = [
    {name = "Alvin", email = "quhao317@163.com"},
]
dependencies = [
    "pdm-lib @ file:///${PROJECT_ROOT}/../lib"
]
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
lint = [
    "mypy>=1.15.0",
    "autopep8>=2.3.2",
]
test = [
    "pytest>=8.3.5",
]

[tool.pdm]
distribution = false

[tool.pdm.scripts]
start = "main.py"
check = { composite = ["mypy .", "autopep8 ."] }
test = "pytest tests"
clean = { call = "clear:main" }

[tool.pycln]
all = true

[tool.mypy]
python_version = "3.13"
strict = true
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
disallow_untyped_decorators = false
check_untyped_defs = true
exclude = ['^.venv\.py$', '^.test\.py$']

[tool.autopep8]
max_line_length = 120
ignore = ['E501', 'W6']
in-place = true
recursive = true
jobs = -1
aggressive = 3

[tool.pytest.ini_options]
addopts = [
    '-vvs',
]
