[project]
name = "toolchain-pdm-app"
version = "1.0.0"
authors = [
    { name = "Alvin", email = "quhao317@163.com" },
]
dependencies = [
    "toolchain-pdm-lib @ file:///${PROJECT_ROOT}/../lib"
]
requires-python = ">=3.13"
readme = "README.md"
license = { text = "MIT" }

[dependency-groups]
lint = [
    "autopep8>=2.3.2",
    "pycln>=2.5.0",
]
test = [
    "pytest-sugar>=1.0.0",
    "pytest>=8.4.0",
]
type = [
    "mypy-extensions>=1.1.0",
    "mypy>=1.16.0",
]

[tool.pdm]
distribution = false

[tool.pdm.scripts]
lint = { composite = [
    "pycln --config=pyproject.toml",
    "autopep8 .",
] }
type = { composite = [
    "mypy",
] }
test = "pytest"
check = { composite = [
    "lint",
    "type",
    "test",
] }
start = { call = "main:main" }
clean = { call = "clear:main" }
type-install = "mypy --install-types"

[tool.pycln]
path = "."
all = true
exclude = '\.history'

[tool.mypy]
files = [
    ".",
]
strict = true
check_untyped_defs = true
disallow_untyped_decorators = false
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true
exclude = '\.history'

[tool.autopep8]
aggressive = 3
ignore = [
    'E501',
    'W6',
]
in-place = true
jobs = -1
max_line_length = 120
recursive = true
exclude = '.history'

[tool.pytest.ini_options]
addopts = [
    '-s',
]
testpaths = [
    'tests',
]
