version: "3"
services:
  postgres:
    image: "postgres:13"
    container_name: "postgres"
    environment:
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=study_python"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - "postgres-network"
networks:
  postgres-network:
    external: false
volumes:
  postgres-data:
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
